name: background_service_ios
description: iOS implementation of the background_service plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

flutter:
  plugin:
    implements: background_service
    platforms:
      ios:
        pluginClass: BackgroundServicePlugin
        dartPluginClass: BackgroundServiceIOS

dependencies:
  flutter:
    sdk: flutter
  background_service_platform_interface:
    path: ../background_service_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^5.1.0
